name: dotnetcoreManualApproval

on:
  push:
    branches: none # [ main ]
  pull_request:
    branches: none # [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build-dotnet-app:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: app-dotnet
        
    steps:
    - uses: trstringer/manual-approval@v1    #  Manual approval
      with:
          secret: ${{ github.TOKEN }}
          approvers: srajib429,blossom429
          minimum-approvals: 1
          
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
  
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Release  
      
    - name: SFTP uploader
      uses: wangyucode/sftp-upload-action@v2.0.2
      with:
        host: ${{secrets.HOST}}
        port: ${{secrets.PORT}}
        username: ${{secrets.USERNAME}}
        password: ${{secrets.PWD}}
        localDir: '/home/runner/work/StudyGithubActionPublic/StudyGithubActionPublic/app-dotnet/bin/Release/net6.0/publish/'
        remoteDir: '/home/tomcat/code'
     
      
   
      
   