name: dotnetcore_sendmail_approval

on:
  push:
    branches: none # [ main ]
  pull_request:
    branches: none # [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build-dotnet-app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app-dotnet
        
    steps:
    - uses: dawidd6/action-send-mail@v3   # Send Mail
      with:
        #connection_url: ${{secrets.MAIL_CONNECTION}}
        server_address: smtp.gmail.com
        server_port: 465
        secure: true
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Github Actions job result
        to: rsarkar@pathinfotech.com
        from: srajib2271@gmail.com
        html_body: 'Hi Team,<br><br>nBuild job of ${{github.repository}} requires appoval for build, please visits Github portal and approve with comment as approve, approved or yes.<br><br><br><br> Regards,<br> GitHub Action bot'
    - uses: trstringer/manual-approval@v1    #  Manual approval
      with:
          secret: ${{ github.TOKEN }}
          approvers: srajib429
   
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
  
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Release  
      
    - name: SFTP uploader
      uses: wangyucode/sftp-upload-action@v2.0.2
      with:
        host: ${{secrets.HOST}}
        port: ${{secrets.PORT}}
        username: ${{secrets.USERNAME}}
        password: ${{secrets.PWD}}
        localDir: '/home/runner/work/StudyGithubActionPublic/StudyGithubActionPublic/app-dotnet/bin/Release/net6.0/publish/'
        remoteDir: '/home/tomcat/code'
     
      
   
      
   